package com.example.rhodoswidget

internal val compassTips = listOf(
    CompassTip("Essen", "Taverne Akti", "Leckeres Essen, faire Preise und freundlicher Service.", "Besonders häufig empfohlen"),
    CompassTip("Essen", "Stama", "Kleine Speisekarte und sehr herzlicher Service.", "Persönliche Empfehlung aus der Gruppe"),
    CompassTip("Strände", "Tsambika / Tsampika", "Weitläufiger Strand mit Restaurant und Liegen auf der linken Seite.", "Kann tagsüber sehr voll werden", CompassTipKind.CAUTION),
    CompassTip("Strände", "Stegna", "Schöner Strand mit guten Möglichkeiten zum Essen.", "In der Hauptzeit mehr Andrang", CompassTipKind.NOTE),
    CompassTip("Strände", "Pefkoi Plakia Beach", "Ruhige Pause am Meer bei der Blue Waves Cantine.", "Tipp für einen entspannten Strandtag"),
    CompassTip("Strände", "Elli Beach", "Zentraler Stadtstrand mit derzeit gemischten Erfahrungen.", "Sauberkeit vor Ort prüfen", CompassTipKind.CAUTION),
    CompassTip("Ausflüge", "Mandraki vor Sonnenaufgang", "Ruhiges Licht, Altstadtkulisse und einlaufende Schiffe.", "Am besten sehr früh besuchen"),
    CompassTip("Mobilität", "Mietwagenbedingungen prüfen", "Selbstbeteiligung, Kaution, Shuttle und Versicherung schriftlich bestätigen lassen.", "Vor der Buchung klären", CompassTipKind.CAUTION),
    CompassTip("Unterkünfte", "Elysium bei Faliraki", "Strand, Service und Lage wurden positiv hervorgehoben.", "Einzelne sehr positive Erfahrung", CompassTipKind.NOTE),
    CompassTip("Unterkünfte", "Kresten Palace", "Mehrere positive Rückmeldungen zu Hotel und Aufenthalt.", "Steiler Weg zum Strand", CompassTipKind.CAUTION),
    CompassTip("Unterkünfte", "Lydia Maris Resort", "Von einem wiederkehrenden Gast erneut positiv bewertet.", "Erfahrung eines Stammgasts", CompassTipKind.NOTE),
    CompassTip("Unterkünfte", "Esperides Beach Family", "Familienhotel mit Pool, direkter Meerlage und gutem Essen.", "Gut für Familien"),
    CompassTip("Unterkünfte", "Blue Sea Beach", "Positiver erster Eindruck in direkter Strandlage.", "Für Abendbummel außerhalb von Faliraki", CompassTipKind.CAUTION),
    CompassTip(
        category = "Essen",
        title = "Melekouni probieren",
        description = "Der rhodische Sesam-Honig-Riegel ist eine typische Süßigkeit der Insel und ein gutes kleines Mitbringsel.",
        note = "In Bäckereien und Läden nach lokaler Herstellung fragen",
        location = "Inselweit",
        journey = "leicht zu finden",
        tags = listOf("regional", "süß", "Mitbringsel"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitgreece.gr/blog/travel-tips/1257/we-serve-the-aegean/"
    ),
    CompassTip(
        category = "Essen",
        title = "Lakani auf der Karte suchen",
        description = "Lakani gehört zu den traditionellen Gerichten von Rhodos und wird langsam im Ofen gegart.",
        note = "Nicht jede Taverne bietet das Gericht täglich an",
        location = "Traditionelle Tavernen",
        journey = "vorher nachfragen",
        tags = listOf("regional", "herzhaft", "Taverne"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitgreece.gr/blog/travel-tips/1257/we-serve-the-aegean/"
    ),
    CompassTip(
        category = "Essen",
        title = "Dodekanes-Gebäck testen",
        description = "Xerotigana und Pastelaries stehen für die süße Küche der Dodekanes-Inseln.",
        note = "Ideal als Dessert oder zum Kaffee",
        location = "Bäckereien und Tavernen",
        journey = "inselweit",
        tags = listOf("Dessert", "regional", "Kaffee"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitgreece.gr/experiences/gastronomy/traditional-cuisine/local-flavours-of-the-greek-cuisine/"
    ),
    CompassTip(
        category = "Ausflüge",
        title = "Sieben Quellen im Schatten",
        description = "Quellen, Waldwege und der schmale Wassertunnel machen Epta Piges zu einem angenehmen Naturziel nahe Kolymbia.",
        note = "Im Tunnel kann es nass und rutschig sein",
        kind = CompassTipKind.CAUTION,
        location = "Epta Piges",
        journey = "nahe Kolymbia",
        tags = listOf("Natur", "Schatten", "ohne Auto möglich"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitrhodes.com/what-to-see/sightseeing/seven-springs"
    ),
    CompassTip(
        category = "Ausflüge",
        title = "Kallithea: Architektur und Badestopp",
        description = "Die restaurierte Thermenanlage verbindet historische Architektur, Kieselmosaike und eine kleine Badebucht.",
        note = "Öffnungszeiten und Eintritt am Ausflugstag prüfen",
        location = "Kallithea Springs",
        journey = "Richtung Rhodos-Stadt",
        tags = listOf("Kultur", "Baden", "Halbtag"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitrhodes.com/what-to-see/sightseeing/kallithea-springs"
    ),
    CompassTip(
        category = "Ausflüge",
        title = "Lindos gleich morgens",
        description = "Dorf und Akropolis werden stark besucht. Ein früher Start macht Wege, Hitze und Warteschlangen angenehmer.",
        note = "Feste Schuhe und Wasser mitnehmen",
        location = "Lindos",
        journey = "Bus ab Kolymbia",
        tags = listOf("Kultur", "früh", "Halbtag"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitrhodes.com/what-to-see/villages/kalathos"
    ),
    CompassTip(
        category = "Ausflüge",
        title = "Anthony-Quinn-Bucht",
        description = "Die kleine, von Felsen und Pinien eingerahmte Bucht ist ein schönes Ziel für klares Wasser und eine Badepause.",
        note = "Wegen der kompakten Bucht möglichst früh ankommen",
        location = "Ladiko",
        journey = "nördlich von Kolymbia",
        tags = listOf("Baden", "Bucht", "früh"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitrhodes.com/what-to-see/beaches/anthony-quinn-bay"
    ),
    CompassTip(
        category = "Ausflüge",
        title = "Prasonisi als ganzer Reisetag",
        description = "Am Südende treffen zwei unterschiedlich windige Küstenseiten aufeinander – spektakulär, aber weit entfernt.",
        note = "Wind, Fahrzeit und Rückweg vorab einplanen",
        kind = CompassTipKind.CAUTION,
        location = "Südspitze von Rhodos",
        journey = "Tagesausflug mit Auto",
        tags = listOf("Landschaft", "Wind", "Tagesausflug"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitrhodes.com/what-to-see/beaches/prasonisi-beach"
    ),
    CompassTip(
        category = "Mobilität",
        title = "September-Fahrplan neu prüfen",
        description = "KTEL veröffentlicht saisonale Fahrpläne. Die heute sichtbaren Zeiten sind nicht automatisch für den 20.09.2026 gültig.",
        note = "Kurz vor Abreise und nochmals vor Ort aktualisieren",
        kind = CompassTipKind.CAUTION,
        location = "Kolymbia Beach",
        journey = "KTEL Ostküste",
        tags = listOf("Bus", "September", "Fahrplan"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.ktelrodou.gr/schedule/"
    ),
    CompassTip(
        category = "Mobilität",
        title = "Rückfahrt zuerst planen",
        description = "Bei Zielen mit wenigen Direktverbindungen zuerst die letzte passende Rückfahrt sichern und danach den Tagesablauf planen.",
        note = "Besonders wichtig für Tsambika und Sieben Quellen",
        location = "Ab Kolymbia",
        journey = "Busausflüge",
        tags = listOf("Bus", "Rückfahrt", "ohne Auto"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.ktelrodou.gr/schedule/"
    ),
    CompassTip(
        category = "Kolymbia",
        title = "Eukalyptusallee am Abend",
        description = "Die von Eukalyptusbäumen gesäumte Straße zum Strand eignet sich für einen ruhigen Spaziergang oder eine kleine Radrunde.",
        note = "In der Dämmerung auf Verkehr und Sichtbarkeit achten",
        kind = CompassTipKind.NOTE,
        location = "Kolymbia",
        journey = "nah am Urlaubsort",
        tags = listOf("Spaziergang", "Abend", "Fahrrad"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitrhodes.com/what-to-see/beaches/kolymbia-beach"
    ),
    CompassTip(
        category = "Kolymbia",
        title = "Entspannter Strandtag vor Ort",
        description = "Kolymbia Beach gilt als eher ruhiger Ferienstrand mit klarem Wasser und weniger Partystimmung als größere Badeorte.",
        note = "Für heiße Tage Schatten oder Sonnenschirm einplanen",
        location = "Kolymbia Beach",
        journey = "zu Fuß je nach Hotel",
        tags = listOf("Strand", "ruhig", "nah"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitrhodes.com/what-to-see/beaches/kolymbia-beach"
    ),
    CompassTip(
        category = "Essen",
        title = "Carrusel: griechische Klassiker",
        description = "Das familiengeführte Restaurant an der Eukalyptusstraße bietet griechische Klassiker, Grillgerichte und vegetarische Optionen.",
        note = "Bei mehreren Vorspeisen lieber teilen – die Portionen werden als großzügig beschrieben",
        location = "Eukalyptusstraße, Kolymbia",
        journey = "zu Fuß je nach Hotel",
        tags = listOf("Kolymbia", "Taverne", "Grill", "vegetarisch"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.carrusel-restaurant.com/"
    ),
    CompassTip(
        category = "Essen",
        title = "Meze bei Ouzaki teilen",
        description = "Eine zentral gelegene griechische Taverne an der Eukalyptusstraße für Meze, Fisch und weitere traditionelle Gerichte.",
        note = "Mehrere kleine Teller bestellen und gemeinsam probieren",
        location = "Eukalyptusstraße, Kolymbia",
        journey = "zu Fuß je nach Hotel",
        tags = listOf("Kolymbia", "Meze", "Taverne", "zu Fuß"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.tripadvisor.co.uk/Restaurant_Review-g635615-d21080739-Reviews-Taverna_Ouzaki-Kolimbia_Rhodes_Dodecanese_South_Aegean.html"
    ),
    CompassTip(
        category = "Essen",
        title = "To Palio Nisaki: Fisch am Meer",
        description = "Die traditionsreiche Fischtaverne liegt direkt am Kolymbia Beach und serviert Tagesfang, Meze und Meeresfrüchte.",
        note = "Tagesfang, Zubereitung und Kilopreis vor der Bestellung bestätigen",
        location = "Kolymbia Beach",
        journey = "zu Fuß oder kurze Taxifahrt",
        tags = listOf("Kolymbia", "Fisch", "Meeresfrüchte", "Meerblick"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://topalionisaki.gr/en/"
    ),
    CompassTip(
        category = "Essen",
        title = "Rosso di Sera: Pizza-Abend",
        description = "Eine italienische Abwechslung in Kolymbia mit Pizza und Pasta sowie vegetarischen und veganen Möglichkeiten.",
        note = "Das Lokal ist auf den Abend ausgerichtet – Öffnungszeit am Besuchstag prüfen",
        location = "Athinon Street, Kolymbia",
        journey = "zu Fuß je nach Hotel",
        tags = listOf("Kolymbia", "Pizza", "Pasta", "vegetarisch"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.visitrhodes.com/restaurants/ristorante--rosso-di-sera"
    ),
    CompassTip(
        category = "Essen",
        title = "Anthoula: Taverne im Grünen",
        description = "Nahe der Abzweigung zu den Sieben Quellen gibt es lokale Gerichte, Meze und Fleisch vom Holzkohlegrill in familiärer Umgebung.",
        note = "Etwas außerhalb – gut mit Epta Piges oder einer kurzen Taxifahrt verbinden",
        location = "Abzweigung Kolymbia Richtung Archipoli",
        journey = "kurze Taxi- oder Autofahrt",
        tags = listOf("nahe Kolymbia", "Taverne", "Grill", "regional"),
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.anthoulataverna.gr/"
    ),
    CompassTip(
        category = "Essen",
        title = "Taverna Michel: familiär und vom Grill",
        description = "Eine kleine familiengeführte Taverne in Kolymbia für griechische Grillgerichte, Meze, Pizza und Gyros.",
        note = "Die jüngsten Bewertungen sind nicht einheitlich – Karte und Tagesform vor Ort einschätzen",
        location = "Kolymbia",
        journey = "zu Fuß je nach Hotel",
        tags = listOf("Kolymbia", "Taverne", "Grill", "zu Fuß"),
        reviewSummary = "Häufig gelobt werden herzlicher Familienservice, Tzatziki, Grillgerichte, großzügige Portionen und ein gutes Preis-Leistungs-Verhältnis. Einzelne aktuelle Stimmen kritisieren dagegen die Lage an der Straße sowie schwankende Qualität und Aufmerksamkeit im Service.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.tripadvisor.co.uk/Restaurant_Review-g635615-d3513149-Reviews-Taverna_Michel-Kolimbia_Rhodes_Dodecanese_South_Aegean.html"
    ),
    CompassTip(
        category = "Essen",
        title = "Taverna Tsambikos: klassische Küche",
        description = "Eine etwas außerhalb gelegene Taverne mit griechischer Hausmannskost, Grillgerichten und vegetarischen Optionen.",
        note = "Für den Abend reservieren und die Anfahrt mit Taxi oder Auto einplanen",
        location = "Straße Kolymbia–Archipoli",
        journey = "kurze Taxi- oder Autofahrt",
        tags = listOf("nahe Kolymbia", "Taverne", "traditionell", "vegetarisch"),
        reviewSummary = "Viele Gäste nennen Moussaka, Mixed Grill und lokale Vorspeisen als Stärken und beschreiben den Empfang als warm und großzügig. Das Lokal liegt abseits des Zentrums; gerade zur Hauptzeit werden Reservierung und eine geplante Rückfahrt empfohlen.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.tripadvisor.co.uk/Restaurant_Review-g635615-d4444048-Reviews-Taverna_Tsambikos-Kolimbia_Rhodes_Dodecanese_South_Aegean.html"
    ),
    CompassTip(
        category = "Essen",
        title = "Food Box: schnell und unkompliziert",
        description = "Eine zwanglose Adresse an der Eukalyptusstraße für Gyros-Pita, Burger, Grillteller, Salate und Crêpes.",
        note = "Gut für einen schnellen Imbiss oder zum Mitnehmen statt für einen ruhigen Taverna-Abend",
        location = "Eukalyptusstraße, Kolymbia",
        journey = "zu Fuß je nach Hotel",
        tags = listOf("Kolymbia", "Gyros", "Burger", "Take-away", "günstig"),
        reviewSummary = "Wiederkehrendes Lob gilt den frisch wirkenden Speisen, großen Portionen, kurzen Wartezeiten und fairen Preisen. Vereinzelt berichten Gäste von weniger aufmerksamem Service oder unterschiedlich kräftig gewürztem Hähnchen.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.tripadvisor.co.uk/Restaurant_Review-g635615-d12938349-Reviews-Food_Box-Kolimbia_Rhodes_Dodecanese_South_Aegean.html"
    ),
    CompassTip(
        category = "Essen",
        title = "Limanaki: Meeresblick und Seafood",
        description = "Ein Restaurant oberhalb der Küste mit Fisch, Meeresfrüchten, Pasta und weitem Blick über das Wasser.",
        note = "Die Aussicht ist die sichere Stärke – Tagesfang und Preis vor der Bestellung klären",
        location = "Küste von Kolymbia",
        journey = "zu Fuß, Taxi oder Auto je nach Hotel",
        tags = listOf("Kolymbia", "Fisch", "Meeresfrüchte", "Meerblick"),
        reviewSummary = "Sehr häufig werden die Lage, der Sonnenuntergang, Cocktails und Gerichte wie Seafood-Pasta hervorgehoben. Neuere Bewertungen sind beim Essen und Service geteilt: Manche erleben einen besonderen Abend, andere empfinden Qualität oder Preis-Leistung als durchschnittlich.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.tripadvisor.co.uk/Restaurant_Review-g635615-d4600258-Reviews-Limanaki_Seafood_Restaurant-Kolimbia_Rhodes_Dodecanese_South_Aegean.html"
    ),
    CompassTip(
        category = "Essen",
        title = "Mylos: besonderer Abend am Meer",
        description = "Ein gehobeneres À-la-carte-Restaurant am Atlantica Imperial Resort mit moderner griechisch-mediterraner Küche.",
        note = "Vorher klären, ob externe Gäste reservieren können und welcher Preis gilt",
        location = "Atlantica Imperial Resort, Kolymbia",
        journey = "zu Fuß oder kurzes Taxi je nach Hotel",
        tags = listOf("Kolymbia", "gehoben", "Meerblick", "Reservierung"),
        reviewSummary = "Viele Rezensionen loben die sorgfältige Präsentation, authentische Aromen, großzügige Portionen, den Meerblick und sehr aufmerksamen Service. Das Preisniveau ist höher und zahlreiche Berichte stammen von Hotelgästen mit inkludiertem Restaurantbesuch.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.tripadvisor.com/Restaurant_Review-g635615-d12833701-Reviews-Mylos_A_La_Carte_Restaurant-Kolimbia_Rhodes_Dodecanese_South_Aegean.html"
    ),
    CompassTip(
        category = "Supermärkte",
        title = "Sklavenitis Kolymbia: großer Einkauf",
        description = "Der größere Vollsortimenter an der Straße Rhodos–Lindos bietet Frischetheken, Backwaren, Obst, Fertiggerichte und einen Parkplatz.",
        note = "Für einen umfangreichen Einkauf sinnvoller als kleine touristische Minimärkte",
        location = "Rhodos–Lindos-Straße bei Kolymbia",
        journey = "am einfachsten mit Auto oder Taxi",
        tags = listOf("Kolymbia", "Supermarkt", "Lebensmittel", "Parkplatz"),
        reviewSummary = "Besucher beschreiben den Markt als gut sortiert, preislich vernünftig und praktisch für einen größeren Vorratseinkauf; auch Personal, Parkplatz und warme Speisen werden positiv erwähnt. Sonntags und an Feiertagen können andere Öffnungszeiten gelten oder der Markt geschlossen sein.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.sklavenitis.gr/anakoinoseis/"
    ),
    CompassTip(
        category = "Supermärkte",
        title = "Zeus: zentraler Ferienmarkt",
        description = "Ein zentraler Supermarkt und Tourist Shop in Kolymbia für Getränke, Snacks, Strandbedarf und Souvenirs.",
        note = "Praktisch zu Fuß; bei einem großen Einkauf Preise mit Sklavenitis vergleichen",
        location = "Kolymbia",
        journey = "zu Fuß je nach Hotel",
        tags = listOf("Kolymbia", "Supermarkt", "Strandbedarf", "zu Fuß"),
        reviewSummary = "Viele Rezensionen nennen die große Auswahl, hilfsbereites Personal und für den Ferienort ordentliche Preise. Andere ordnen Zeus klar als Tourist Shop ein und finden nicht jedes Produkt besonders günstig – für Bequemlichkeit und kleine Einkäufe ist er vor allem praktisch.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://citymaps.gr/souper-market/rodos/zeus-supermarket-tourist-shop/"
    ),
    CompassTip(
        category = "Souvenirs",
        title = "Secret Rhodes: handgemachte Andenken",
        description = "Ein kleiner Laden an der Eukalyptusstraße mit Keramik, Schmuck, Naturkosmetik, Olivenölseife und handgemachten Dekorationen.",
        note = "Gut für individuellere Mitbringsel statt der üblichen Massenware",
        location = "Eukalyptusstraße, Kolymbia",
        journey = "zu Fuß je nach Hotel",
        tags = listOf("Kolymbia", "Souvenirs", "handgemacht", "Naturkosmetik"),
        reviewSummary = "Die vorhandenen Rezensionen heben originelle Handarbeiten, freundliche Beratung, lokale Produkte und faire Preise hervor. Die Bewertungsbasis ist allerdings deutlich kleiner als bei großen Attraktionen; Öffnungszeiten deshalb am Besuchstag prüfen.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://wanderlog.com/place/details/10072130/secret-rhodes-sv5swu"
    ),
    CompassTip(
        category = "Souvenirs",
        title = "Michail: Keramik aus Familienhand",
        description = "Ein familiengeführter Kunsthandwerksladen mit handgefertigter Keramik, Gefäßen und dekorativen Einzelstücken.",
        note = "Bei Fluggepäck Verpackung und Transport zerbrechlicher Stücke direkt klären",
        location = "bei Kolymbia",
        journey = "Taxi oder Auto",
        tags = listOf("nahe Kolymbia", "Souvenirs", "Keramik", "Kunsthandwerk"),
        reviewSummary = "Gäste loben besonders die sichtbare Handarbeit, kreative Formen, die familiäre Atmosphäre und persönliche Erklärungen zur Herstellung. Für einen kurzen Einkaufsbummel ist die Lage weniger spontan; für gezielte Keramik-Souvenirs lohnt der eigene Stopp.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.tripadvisor.fr/Attraction_Review-g635615-d23862457-Reviews-Michail_Artistic_Craft_and_Artifacts-Kolimbia_Rhodes_Dodecanese_South_Aegean.html"
    ),
    CompassTip(
        category = "Regionale Produkte",
        title = "Artistic Village: Keramik und Galerie",
        description = "Eine familiengeführte Keramikwerkstatt mit Galerie und kleinem Museum zwischen Afandou und Kolymbia.",
        note = "Mehr als ein Shop: etwas Zeit zum Ansehen der Werkstatt und Einzelstücke einplanen",
        location = "Straße Rhodos–Lindos bei Kolymbia",
        journey = "Auto oder Taxi",
        tags = listOf("nahe Kolymbia", "Keramik", "Galerie", "regional"),
        reviewSummary = "Viele Besucher sprechen von außergewöhnlicher, vor Ort gefertigter Keramik, großer Auswahl und freundlichen Erklärungen der Familie. Besonders positiv fällt auf, dass die Stücke als origineller wahrgenommen werden als typische Souvenirware.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.tripadvisor.co.uk/Attraction_Review-g635615-d6557395-Reviews-Artistic_Village_Contemporary_Art_Art_gallery_Museum_of_Ceramic_Art-Kolimbia_Rhod.html"
    ),
    CompassTip(
        category = "Regionale Produkte",
        title = "Olive Oil Factory: Öl mit Einblick",
        description = "Eine familiengeführte Station in Archangelos, die traditionelle und moderne Ölherstellung sowie Verkostungen verbindet.",
        note = "Verkostung nutzen, aber Preise und Mengen vor dem Kauf vergleichen",
        location = "Archangelos",
        journey = "Auto oder Taxi",
        tags = listOf("Archangelos", "Olivenöl", "Verkostung", "regional"),
        reviewSummary = "Positiv beschrieben werden die persönliche Führung, der Vergleich alter und neuer Pressmethoden und die Verkostung von Öl und lokalen Produkten. Kritische Stimmen empfinden die Verkaufspreise als hoch – anschauen und probieren kann sich trotzdem lohnen.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://www.tripadvisor.co.uk/Attraction_Review-g1175544-d8355871-Reviews-Olive_Oil_Factory-Archangelos_Rhodes_Dodecanese_South_Aegean.html"
    ),
    CompassTip(
        category = "Regionale Produkte",
        title = "Traditional Greek Kiosk: probieren und mitnehmen",
        description = "Ein kleiner Spezialitätenladen am Symi-Platz in Rhodos-Stadt mit Olivenöl, Honig, Kräutern, Gewürzen und Likören.",
        note = "Nur als Teil eines Tags in Rhodos-Stadt einplanen – nicht für einen schnellen Einkauf in Kolymbia",
        location = "Symi-Platz, Rhodos-Stadt",
        journey = "mit Bus oder Auto nach Rhodos-Stadt",
        tags = listOf("Rhodos-Stadt", "Olivenöl", "Honig", "Verkostung"),
        reviewSummary = "Wiederkehrend gelobt werden fachkundige, unaufdringliche Beratung, großzügiges Probieren und die Auswahl an Öl, Honig, Kräutern und besonderen Cremes. Viele Gäste empfinden die Preise im Vergleich zur Altstadt als fair; die Anfahrt lohnt vor allem zusammen mit einem Stadtbesuch.",
        source = CompassTipSource.RESEARCHED,
        sourceUrl = "https://wanderlog.com/place/details/12856969/traditional-greek-kiosk"
    )
).let(::attachCompassTipIds)
